### PR TITLE
Support color temperature for Shelly Duo

### PR DESCRIPTION
**Pull request by 314eter**
Since the last firmware update, Shelly Duo supports changing color temperature with MQTT. The status contains a `white` and `temp` value, but only `temp` can be changed. Since the MQTT integration does not support changing the temperature range (I opened home-assistant/core#32613), I scaled the range of the Shally DUO to the default range of Home Assistant.

### CODE REVIEW

**Comment by bieniu** [comment]
@314eter Could you explain your conversion method to me? I thought that conversion from `kelvin` to `mired` uses the formula:
```
1000000/kelvin=mired
```

**Comment by 314eter** [comment]
The range of the Shelly Duo is 2700K-6500K, which is 370-153 mired. But Home Assistant uses a range of 500-153 mired. So I did a linear transformation from 2700-6500K to 500-153 mired.

**Comment by 314eter** [comment]
There is still a bug in the firmware. If the brightness is changed without setting the temperature (`{"turn":"on","brightness":50}`), the temperature is reset to 2700K.

**Comment by staff1703** [comment]
> The range of the Shelly Duo is 2700K-6500K, which is 370-153 mired. But Home Assistant uses a range of 500-153 mired. So I did a linear transformation from 2700-6500K to 500-153 mired.

I think we should not recalculate mireds into "shelmireds" just because home assistant has problems. I would stick to real mireds and eventually when HA provides properties to set boundaries for mireds per mqtt device, enhance the config with proper values

**Comment by bieniu** [comment]
@314eter I agree with @staff1703, we shouldn't convert `mireds` to own scale.

**Pull request closed without merging**
