### PR TITLE
Remove white_value because of deprecation

### PR DESCRIPTION
**Pull request by bieniu**

### CODE REVIEW

**Comment by Benni1123** [comment]
Hello! Since the update, I can no longer control the white channel on my Shellys (RGBW2, Bulb). 
Please reinstate this function.

**Comment by bieniu** [comment]
`white_value` is deprecated and will be removed from HA.

**Comment by Benni1123** [comment]
How should I then control the white channel from the Shellys?

**Comment by bieniu** [comment]
I think this is currently not possible via MQTT. Shelly has to change the firmware.

**Comment by Benni1123** [comment]
Screenshot_2022-06-08-10-00-09-44_c3a231c25ed346e59462e84656a70e50
So far it still works. As long as I don't do the update, I can control the white channel so far.

**Pull request merged**
