### PR TITLE
TRV SENSOR_MINIMAL_VALVE_REPORT

### PR DESCRIPTION
**Pull request by GergelyT**
Introducing a new sensor for Minimal Valve Report parameter (from firmware 2.2.1)

### CODE REVIEW

**Comment by bieniu** [comment]
This is a static value in most cases, What is the benefit/value for the user from adding such a sensor?

**Comment by GergelyT** [comment]
This is a configurable parameter on the TRV. If you use it for not starting the boiler below this valve position (and this is the purpose of this value, I think) then you can use this sensor at automation which turn on the boiler.  Valve Position < Valve Position Reported to be open = Valve should be considered as closed.

**Comment by GergelyT** [comment]
Hopefuly only once, when configuring the system. But if you have more radiators, this value could be different at each of them. Anyway, if there is a configurable parameter, which is reported via mqtt by the device, it is better to be included in the integration  then not :)

Apart from that this is just a proposal - I have this change locally, that's why I shared it back. It is your decision if you include in your code or not

**Comment by GergelyT** [comment]
One more thing I realised: I wrote KEY_ENABLED_BY_DEFAULT: True, but it should be false of course

**Comment by GergelyT** [comment]
I see that  you worked on my request on another branch. Thanks for the work. I'll close this PR and will test your solution first.

**Comment by bieniu** [comment]
IMO, it would make more sense to create a number entity to configure the min valve position report, similarly to the min valve position

obraz

**Pull request closed without merging**
